[package]
name = "pwd-076"
version = "0.1.0"
authors = ["Jonas Berlin <xkr47@outerspace.dyndns.org>"]
edition = "2018"

[dependencies]
clap = "2.33"
itertools = "0.9"
regex = "1.3"

[[bin]]
name = "ch-2"
path = "ch-2.rs"
