[package]
name = "pwd-073"
version = "0.1.0"
authors = ["Jonas Berlin <xkr47@outerspace.dyndns.org>"]
edition = "2018"

[dependencies]
num-traits = "0.2"

[[bin]]
name = "ch-2"
path = "ch-2.rs"

[[bin]]
name = "ch-2-2"
path = "ch-2-2.rs"
